FROM golang:alpine as builder

COPY . /app

WORKDIR /app

RUN apk add --no-cache upx git && \
CGO_ENABLED=0 go build -o gitlabci-composer-update-mr -ldflags "-s -w" . && \
upx -9 gitlabci-composer-update-mr


FROM php:7.4-alpine

RUN apk add --no-cache git bash icu-libs \
&& wget https://getcomposer.org/download/latest-1.x/composer.phar -O /usr/local/bin/composer-1 && chmod +x /usr/local/bin/composer-1 \
&& wget https://getcomposer.org/download/latest-stable/composer.phar -O /usr/local/bin/composer-2 && chmod +x /usr/local/bin/composer-2 \
&& apk add --no-cache --virtual build-dependencies icu-dev \
&& docker-php-ext-install intl pcntl && apk del build-dependencies

COPY --from=builder /app/gitlabci-composer-update-mr /usr/local/bin/gitlabci-composer-update-mr

ENV COMPOSER_HOME="/tmp/"
