FROM golang:1.16-alpine as builder

COPY . /app

WORKDIR /app

RUN CGO_ENABLED=0 go build -o gitlabci-composer-update-mr -ldflags "-s -w" . && \
apk add --no-cache upx && upx -9 gitlabci-composer-update-mr


FROM php:7.3-alpine3.13

RUN apk add --no-cache git bash icu-libs openssh \
&& wget https://getcomposer.org/download/latest-1.x/composer.phar -O /usr/local/bin/composer-1 && chmod +x /usr/local/bin/composer-1 \
&& wget https://getcomposer.org/download/latest-stable/composer.phar -O /usr/local/bin/composer-2 && chmod +x /usr/local/bin/composer-2 \
&& apk add --no-cache --virtual build-dependencies icu-dev \
&& docker-php-ext-install intl && apk del build-dependencies

COPY --from=builder /app/gitlabci-composer-update-mr /usr/local/bin/gitlabci-composer-update-mr

ENV COMPOSER_HOME="/tmp/"
