name: Docker build

on:
  push:
    tags:
      - 'release-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Checkout release tag
        uses: actions/checkout@v2

      - name: Build and push 5.6
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-5.6
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:5.6

      - name: Build and push 7.0
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-7.0
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:7.0

      - name: Build and push 7.1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-7.1
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:7.1

      - name: Build and push 7.2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-7.2
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:7.2

      - name: Build and push 7.3
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-7.3
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:7.3

      - name: Build and push 7.4
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-7.4
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:7.4

      - name: Build and push 8.0
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-8.0
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:8.0

      - name: Build and push 8.1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-8.1
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:8.1
