name: Docker build

on:
  push:
    tags:
      - 'release-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Get release tag
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout release tag
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag_name.outputs.VERSION }}

      - name: Build and push 5.6
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-5.6
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:5.6

      - name: Build and push 7.0
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-7.0
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:7.0
